### ISSUE TITLE
Term 'pip' not recognised

### ISSUE THREAD

**Issue by PangWuGui** [SamPom100/UnusualVolumeDetector#25]
Hey I have absolutely no idea what I'm doing, and when I type pip requirements etc. into the terminal I get: 

pip install -r requirements.txt     
pip : The term 'pip' is not recognized as the name of a cmdlet, function, script file, or        
operable program. Check the spelling of the name, or if a path was included, verify that the     
path is correct and try again.
At line:1 char:1
+ pip install -r requirements.txt
+ ~~~
    + CategoryInfo          : ObjectNotFound: (pip:String) [], CommandNotFoundException
    + FullyQualifiedErrorId : CommandNotFoundException

I'm guessing there's something very basic I'm doing wrong here, like running the script properly.

**Comment by a-github-username** [comment]
This isn't an issue with the code, it's an issue with you.

**Comment by Connor9994** [comment]
The line:

`import pip`

should be used if you're trying it in a Windows CMD of Python.

**Comment by PangWuGui** [comment]
> The line:
> 
> `import pip`
> 
> should be used if you're trying it in a Windows CMD of Python.

Thanks Connor! When I do this, I get the same message, just substituting 'import' for pip, ie 'The term 'import' is not recognised etc.'

**Comment by Connor9994** [comment]
Ahh you're new, new. Yeah python is always a pain in the ass in console imo (so my actual suggestion would be to use a real IDE to edit/run the code).

If you want to run it in CMD, python will need to be in your environmental variables (windows) or you will need to call the python exe from its specific location. 

Let's say it's already installed into the environment

Open CMD

`python`

`>>>> import pip

pip -install`

**Comment by PangWuGui** [comment]
Yeah, sorry about the stupid questions -- I realise this is a me issue not a code issue.

I'm using VS Code and both it and python are installed into the environment. This is what I get now:

![UVD](https://user-images.githubusercontent.com/69049105/89058779-f2e05a80-d32d-11ea-9269-22c00f1d077d.JPG)

**Comment by Connor9994** [comment]
Ahh so you're actually in powershell which (in my experience) requires the `.\` before the location to specify look for this file in this folder. A good way to find what the application wants is to type "r" TAB and see if the auto fill corrects it. 
![15962150834016841495968670964513](https://user-images.githubusercontent.com/39637206/89059032-0e476780-d326-11ea-9de1-47d96149ba3b.jpg)

For instance in my root directory I typed t then TAB and it cycles through all of the files starting with t (they're folders so it adds the \ afterwards)

**Comment by Jhongithubuser** [comment]
Hi Pang,
I had the same Problem u need to install phyton 
https://www.python.org/downloads/
when installing go to customized installation

![image](https://user-images.githubusercontent.com/69053215/89062165-3fe02300-d366-11ea-8660-15aab2daa6bc.png)

then on the next page you need to check "add Phyton to environmental variables"

![image](https://user-images.githubusercontent.com/69053215/89062266-6dc56780-d366-11ea-9fb1-573be2175aa0.png)

let the program install 

after installation 

let this website guide you it helped me a lot:

https://code.visualstudio.com/docs/python/python-tutorial

when you have your phyton intepreter set up 

open in vsc the market_scanner .py file click the run button 
![image](https://user-images.githubusercontent.com/69053215/89062932-99951d00-d367-11ea-82a8-8295e7039af8.png)
then you will get errors because he cant find the variables

then type in the terminal the line  pip install -r requirements.txt    the phyton intepreter has to be selected

![image](https://user-images.githubusercontent.com/69053215/89063087-d9f49b00-d367-11ea-8b2d-34888fbde3f8.png)

then it should work and the script is running:)

BR

**Comment by PangWuGui** [comment]
Mmmhhh so that didn't work either, I kept getting the same message and I couldn't get it to auto-fill/cycle through, but I tried pip install and then I copy-pasted the 7 lines of requirements, and 6 of them were installed but yfinance still not :( Now it's like this:

![UVD1](https://user-images.githubusercontent.com/69049105/89063086-8d906780-d335-11ea-93e6-3cbceef9ca0d.JPG)

**Comment by PangWuGui** [comment]
Oh cheers Jhongithubuser, I'll try that out!

**Comment by Jhongithubuser** [comment]
:+1:

**Comment by PangWuGui** [comment]
Ayo that did the trick! Thank you so much guys <3
